#-------------------------------
# General Site Settings
title: Natasha....
#logo: logo.svg # You can add own logo.
description: This is my personal website to showcase my work in the field of Art and science. 


#-------------------------------
# Author Settings
author:
  name: Natasha Jaiswal
  image: ../images/01.jpg
  say-hello: Hello, I’m <strong>Natasha Jaiswal</strong>
  bio: Designs, talks, and writes about <strong>Science</strong>, <strong>Research</strong>, <strong>Atrs</strong>, and Lifestyle. I share paintings, design tutorials, free resources and inspiration. Loves <a href="#">music</a> & and <a href="#">painting</a>.


#-------------------------------
# Contact links
twitter: https://twitter.com/NatashaJaiswa01 # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/njaiswal01/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
